name: Run tests against branch

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches-ignore:
      - main

jobs:
  terraform_lint:
    name: Terraform lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.5.0"
      - name: Terraform Lint
        run: terraform fmt --recursive --check
        
  test-backoffice:
     name: Test backoffice
     uses: ./.github/workflows/_reusable-backoffice-test.yml
     with:
       environment: ci-test
       dotnet-version: "8.0.x"
     secrets:
       env_file: ${{ secrets.BACKOFFICE_ENV_FILE }}

  test-webapp:
    name: Test webapp
    uses: ./.github/workflows/_reusable-webapp-test.yml
    with:
      working-directory: webapp
    secrets:
      testing_webapp_env_file: ${{ secrets.TESTING_WEBAPP_ENV_FILE }}
      
  end_to_end_tests:
    name: End-to-end tests
    needs:
      - terraform_lint
      - test-webapp
      - test-backoffice
    uses: ./.github/workflows/_reusable-end-to-end-tests.yml
    with:
      image-tag: ${{ github.sha }}
      environment: ci-test
    secrets:
      testing_webapp_env_file: ${{ secrets.TESTING_WEBAPP_ENV_FILE }}
      testing_backoffice_env_file: ${{ secrets.BACKOFFICE_ENV_FILE }}
