name: Webapp pipeline
on:
  workflow_call:
    inputs:
      environment:
        description: >
          The environment to which the application should be deployed.  Must be one of development/staging/production
          and must match the terraform_workspace input.
        type: string
        required: true
      image_tag:
        description: The tag to add to the published Docker image, e.g. "v1.0.1"
        type: string
        required: true
    secrets:
      registry_url:
        description: The URL of the registry where the image should be published
        required: true
      repository_name:
        description: The name of the image to be published
        required: true
      aws_role_arn:
        required: true
      env_file:
        description: The contents of the environment file
        required: true

jobs:
  test:
    name: Test webapp
    uses: ./.github/workflows/webapp-test.yml
    with:
      working-directory: webapp

  publish:
    name: Publish webapp
    needs: [test]
    uses: ./.github/workflows/publish.yml
    with:
      image_tag: ${{ inputs.image_tag }}
      environment: ${{ inputs.environment }}
      working-directory: webapp
    secrets:
      registry_url: ${{ secrets.registry_url }}
      repository_name: ${{ secrets.repository_name }}
      aws_role_arn: ${{ secrets.aws_role_arn }}
      env_file: ${{secrets.env_file}}



